const router = require("express").Router();
const {
  createBooking,
  deleteBooking,
  getBookings,
  updateBooking,
} = require("../controllers/booking.controller");

/**
 * @swagger
 * /bookings:
 *   post:
 *     summary: Create booking
 *     description: Execute the request to see the actual saved booking in the Server response section.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/BookingCreateInput'
 *         application/x-www-form-urlencoded:
 *           schema:
 *             $ref: '#/components/schemas/BookingCreateInput'
 *     responses:
 *       201:
 *         description: Booking created successfully
 *       400:
 *         description: Validation error
 *       500:
 *         description: Server error
 */
router.post("/", createBooking);

/**
 * @swagger
 * /bookings:
 *   get:
 *     summary: Get all bookings
 *     description: Execute the request to see the actual bookings returned by the server.
 *     responses:
 *       200:
 *         description: List of bookings
 *       500:
 *         description: Server error
 */
router.get("/", getBookings);

/**
 * @swagger
 * /bookings/{bookingId}:
 *   put:
 *     summary: Update booking
 *     description: Execute the request to see the actual updated booking in the Server response section.
 *     parameters:
 *       - in: path
 *         name: bookingId
 *         required: true
 *         schema:
 *           type: string
 *         description: Autogenerated booking ID returned by create booking
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/BookingUpdate'
 *         application/x-www-form-urlencoded:
 *           schema:
 *             $ref: '#/components/schemas/BookingUpdate'
 *     responses:
 *       200:
 *         description: Booking updated successfully
 *       400:
 *         description: Validation error
 *       404:
 *         description: Booking not found
 *       500:
 *         description: Server error
 *   delete:
 *     summary: Delete booking
 *     description: Execute the request to see the actual delete result returned by the server.
 *     parameters:
 *       - in: path
 *         name: bookingId
 *         required: true
 *         schema:
 *           type: string
 *         description: Autogenerated booking ID returned by create booking
 *     responses:
 *       200:
 *         description: Booking deleted successfully
 *       400:
 *         description: Invalid booking ID
 *       404:
 *         description: Booking not found
 *       500:
 *         description: Server error
 */
router.put("/:bookingId", updateBooking);
router.delete("/:bookingId", deleteBooking);

module.exports = router;
